import { describe, expect, it } from 'vitest';
import type { EngineeringAnalysisResult } from '../../engineering/core/engineeringAnalysis';
import type { SimulationRunInput } from '../../engineering/core/simulationRun';
import type { EngineeringAnalysisIpcResponse } from '../ipc/engineeringAnalysisIpc';
import type { EngineeringRunLoadIpcResponse } from '../ipc/engineeringRunIpc';
import { applyEngineeringAnalysisResponse, createApplicationDataFlowState, createBlankEngineeringDraftState, createSampleEngineeringDraftState, getExportablePdfRequest, hydratePersistedEngineeringRun, markAnalysisRunning, setAnalysisInput } from './applicationDataFlow';

const input: SimulationRunInput = { runId:'run-session-1', engineVersion:'v1', createdAtIso:'2026-09-09T00:00:00Z', pipeline:{ targetFlowRateM3s:0.01, densityKgM3:2400, lubricationLayerThicknessM:0.001, bulk:{yieldStressPa:50,plasticViscosityPaS:10}, lubricationLayer:{yieldStressPa:5,plasticViscosityPaS:1}, segments:[{id:'S1',kind:'straight',lengthM:10,pipeRadiusM:0.05,elevationChangeM:0}] } };
const blockedResult: EngineeringAnalysisResult = { runId:'run-session-1', engineVersion:'v1', readiness:{status:'BLOCKED',canExecute:false,findings:[],method:'tolue-engineering-readiness-gate-v2'}, executionStatus:'BLOCKED', inputSnapshotHash:null, simulation:null, resultCenter:null, diagnostics:null, pumpabilityDecision:null, finalOutput:null, reportExport:null, pdfExportRequest:null, visualization3d:null, completeness:'incomplete', method:'tolue-engineering-analysis-orchestrator-v6' };
const blockedSuccess: EngineeringAnalysisIpcResponse = { status:'SUCCESS', errorCode:null, method:'tolue-engineering-analysis-ipc-response-v1', result:blockedResult };

describe('application data flow session lifecycle',()=>{
  it('moves deterministically from IDLE to READY to RUNNING',()=>{const idle=createApplicationDataFlowState();expect(idle.status).toBe('IDLE');const ready=setAnalysisInput(idle,input);expect(ready.status).toBe('READY');expect(ready.input).toEqual(input);expect(ready.input).not.toBe(input);const running=markAnalysisRunning(ready);expect(running.status).toBe('RUNNING');expect(Object.isFrozen(running)).toBe(true);});
  it('creates an editable first-launch sample with project, geometry and pump data',()=>{const sample=createSampleEngineeringDraftState('sample-1','2026-09-11T19:10:00.000Z');expect(sample.status).toBe('READY');expect(sample.input?.projectMetadata?.name).toContain('پروژه نمونه');expect(sample.input?.pipeline.segments).toHaveLength(3);expect(sample.input?.pipeline.segments[0]?.spatial?.startPoint).toEqual({xM:0,yM:0,zM:0});expect(sample.input?.pumpCapability?.capabilityCurve).toHaveLength(3);expect(sample.input?.assumptions).toContain('EXAMPLE_DATA_ONLY_NOT_FOR_ENGINEERING_DECISIONS');expect(sample.input?.assumptions).not.toContain('DRAFT_PLACEHOLDER_VALUES_REPLACE_BEFORE_ENGINEERING_USE');});
  it('creates a zero-valued blocked draft for explicit reset without carrying sample data',()=>{const blank=createBlankEngineeringDraftState('blank-1','2026-09-11T19:11:00.000Z');expect(blank.status).toBe('READY');expect(blank.input?.projectMetadata?.name).toBe('');expect(blank.input?.materials).toEqual([]);expect(blank.input?.pipeline).toMatchObject({targetFlowRateM3s:0,densityKgM3:0,lubricationLayerThicknessM:0,bulk:{yieldStressPa:0,plasticViscosityPaS:0},lubricationLayer:{yieldStressPa:0,plasticViscosityPaS:0},segments:[]});expect(blank.input?.pumpCapability).toBeUndefined();expect(blank.input?.assumptions).toContain('DRAFT_PLACEHOLDER_VALUES_REPLACE_BEFORE_ENGINEERING_USE');});
  it('preserves run identity for a successful IPC response',()=>{const completed=applyEngineeringAnalysisResponse(markAnalysisRunning(setAnalysisInput(createApplicationDataFlowState(),input)),blockedSuccess);expect(completed.status).toBe('SUCCEEDED');expect(completed.activeRunId).toBe(input.runId);expect(completed.analysis?.runId).toBe(input.runId);expect(completed.isStale).toBe(false);expect(getExportablePdfRequest(completed)).toBeNull();});
  it('hydrates an exact persisted run without recomputation or stale state',()=>{const response:EngineeringRunLoadIpcResponse={status:'SUCCESS',input,result:blockedResult,errorCode:null,method:'tolue-engineering-run-load-ipc-response-v1'};const hydrated=hydratePersistedEngineeringRun(response);expect(hydrated.status).toBe('SUCCEEDED');expect(hydrated.input).toEqual(input);expect(hydrated.input).not.toBe(input);expect(hydrated.activeRunId).toBe('run-session-1');expect(hydrated.analysis?.runId).toBe('run-session-1');expect(hydrated.isStale).toBe(false);});
  it('preserves spatial pipeline geometry when hydrating a persisted run',()=>{const spatialInput={...input,pipeline:{...input.pipeline,segments:[{id:'S1',kind:'straight' as const,lengthM:10,pipeRadiusM:0.05,elevationChangeM:0,spatial:{startPoint:{xM:0,yM:0,zM:0},endPoint:{xM:10,yM:0,zM:0}}},{id:'S2',kind:'straight' as const,lengthM:5,pipeRadiusM:0.05,elevationChangeM:0,spatial:{startPoint:{xM:10,yM:0,zM:0},endPoint:{xM:15,yM:0,zM:0},connectedFromSegmentId:'S1'}}]}};const response:EngineeringRunLoadIpcResponse={status:'SUCCESS',input:spatialInput,result:blockedResult,errorCode:null,method:'tolue-engineering-run-load-ipc-response-v1'};const hydrated=hydratePersistedEngineeringRun(response);expect(hydrated.status).toBe('SUCCEEDED');expect(hydrated.input?.pipeline.segments[0]?.spatial?.startPoint).toEqual({xM:0,yM:0,zM:0});expect(hydrated.input?.pipeline.segments[1]?.spatial?.endPoint).toEqual({xM:15,yM:0,zM:0});expect(hydrated.input?.pipeline.segments[1]?.spatial?.connectedFromSegmentId).toBe('S1');expect(hydrated.input).not.toBe(spatialInput);});
  it('fails closed when persisted input/result identities differ',()=>{const response:EngineeringRunLoadIpcResponse={status:'SUCCESS',input:{...input,runId:'other-run'},result:blockedResult,errorCode:null,method:'tolue-engineering-run-load-ipc-response-v1'};const rejected=hydratePersistedEngineeringRun(response);expect(rejected.status).toBe('REJECTED');expect(rejected.errorCode).toBe('APPLICATION-DATA-FLOW-LOAD-RUN-001');expect(rejected.analysis).toBeNull();expect(rejected.activeRunId).toBeNull();});
  it.each([
    { response:{status:'NOT_FOUND',input:null,result:null,errorCode:null,method:'tolue-engineering-run-load-ipc-response-v1'} as EngineeringRunLoadIpcResponse, code:'APPLICATION-DATA-FLOW-LOAD-404' },
    { response:{status:'REJECTED',input:null,result:null,errorCode:'RUN-LOAD-IPC-PERSISTENCE-001',method:'tolue-engineering-run-load-ipc-response-v1'} as EngineeringRunLoadIpcResponse, code:'RUN-LOAD-IPC-PERSISTENCE-001' },
  ])('clears prior engineering outputs on failed persisted load: $code',({response,code})=>{const prior=applyEngineeringAnalysisResponse(markAnalysisRunning(setAnalysisInput(createApplicationDataFlowState(),input)),blockedSuccess);expect(prior.analysis).not.toBeNull();const rejected=hydratePersistedEngineeringRun(response);expect(rejected).toMatchObject({status:'REJECTED',input:null,analysis:null,activeRunId:null,activeInputSnapshotHash:null,errorCode:code,isStale:false});expect(getExportablePdfRequest(rejected)).toBeNull();});
  it('fails closed on rejected analysis without manufacturing outputs',()=>{const rejected=applyEngineeringAnalysisResponse(markAnalysisRunning(setAnalysisInput(createApplicationDataFlowState(),input)),{status:'REJECTED',result:null,errorCode:'ANALYSIS-TEST-REJECT',method:'tolue-engineering-analysis-ipc-response-v1'});expect(rejected.status).toBe('REJECTED');expect(rejected.analysis).toBeNull();expect(rejected.activeRunId).toBeNull();expect(rejected.errorCode).toBe('ANALYSIS-TEST-REJECT');});
  it('marks prior outputs stale when inputs change',()=>{const completed=applyEngineeringAnalysisResponse(markAnalysisRunning(setAnalysisInput(createApplicationDataFlowState(),input)),blockedSuccess);const changed=setAnalysisInput(completed,{...input,runId:'run-session-2'});expect(changed.status).toBe('STALE');expect(changed.isStale).toBe(true);expect(changed.analysis?.runId).toBe('run-session-1');expect(getExportablePdfRequest(changed)).toBeNull();});
  it('rejects a response whose runId does not match the active input',()=>{const running=markAnalysisRunning(setAnalysisInput(createApplicationDataFlowState(),{...input,runId:'run-session-other'}));expect(()=>applyEngineeringAnalysisResponse(running,blockedSuccess)).toThrow('APPLICATION-DATA-FLOW-RUN-001');});
});
