import type { SimulationRunInput } from '../../engineering/core/simulationRun';
import { TOLUE_DESIGN_TOKENS } from './designSystem';
import { appendEngineeringSectionHeader, styleEngineeringButton, styleEngineeringField, styleEngineeringSection } from './engineeringPanelStyle';
import { updatePipelineScalarDraft, updateStraightSegmentDraft, type PipelineScalarPath, type StraightSegmentNumericField } from './engineeringInputDraft';
import { renderLubricationLayerQualificationView } from './lubricationLayerQualificationView';
import { appendStraightSpatialSegmentDraft, updateStraightSpatialSegmentDraft } from './pipelineAuthoring';
import type { PipelinePresentation } from './pipelinePresentation';
import type { PressureCompositionPresentation } from './pressureCompositionPresentation';
import { renderPressureCompositionView } from './pressureCompositionView';
import type { PressureProfilePresentation } from './pressureProfilePresentation';
import { renderPressureProfileView } from './pressureProfileView';
import { assessmentStatusFa } from './persianPresentation';

const EMPTY_PIPELINE: Readonly<PipelinePresentation> = Object.freeze({ completeness: 'incomplete', method: 'tolue-pipeline-pressure-v2', components: Object.freeze([
  Object.freeze({ id: 'straight-friction', label: 'افت فشار اصطکاکی مسیر مستقیم', valuePa: null, source: 'engineering-core' as const }),
  Object.freeze({ id: 'calibrated-local-friction', label: 'افت فشار موضعی کالیبره‌شده', valuePa: null, source: 'engineering-core' as const }),
  Object.freeze({ id: 'elevation', label: 'فشار ناشی از اختلاف ارتفاع', valuePa: null, source: 'engineering-core' as const }),
  Object.freeze({ id: 'required', label: 'فشار موردنیاز', valuePa: null, source: 'engineering-core' as const }),
]), segments: Object.freeze([]) });

export interface PipelineViewActions {
  readonly updateInput: (input: Readonly<SimulationRunInput>) => void;
  readonly selectSegment?: (segmentId: string) => void;
}

export interface PipelineViewOptions {
  readonly selectedSegmentId?: string | null;
}

const formatPressure=(valuePa:number|null):string=>valuePa===null?'—':`${(valuePa/1_000_000).toFixed(3)} مگاپاسکال`;
function requiredNumber(input:HTMLInputElement|null,code:string):number{if(!input||input.value.trim()==='')throw new Error(code);const value=Number(input.value);if(!Number.isFinite(value))throw new Error(code);return value;}
function numericEditor(labelText:string,value:number,onCommit:(value:number)=>void):HTMLElement{const label=document.createElement('label');const caption=document.createElement('span');caption.textContent=labelText;const input=document.createElement('input');input.type='number';input.step='any';input.value=String(value);styleEngineeringField(label,input,caption);const error=document.createElement('small');error.style.minHeight='1.2em';error.style.color=TOLUE_DESIGN_TOKENS.color.statusCritical;input.addEventListener('change',()=>{try{onCommit(Number(input.value));input.setAttribute('aria-invalid','false');error.textContent='';}catch(err){input.setAttribute('aria-invalid','true');error.textContent=err instanceof Error?err.message:'مقدار واردشده معتبر نیست.';}});label.append(caption,input,error);return label;}
function derivedValue(labelText:string,value:string):HTMLElement{const box=document.createElement('div');Object.assign(box.style,{display:'grid',gap:'5px',padding:'9px',border:`1px solid ${TOLUE_DESIGN_TOKENS.color.border}`,borderRadius:TOLUE_DESIGN_TOKENS.radius.sm,background:'rgba(7,16,22,.55)'});const label=document.createElement('small');label.textContent=labelText;label.style.color=TOLUE_DESIGN_TOKENS.color.textMuted;const valueNode=document.createElement('strong');valueNode.textContent=value;Object.assign(valueNode.style,{fontFamily:TOLUE_DESIGN_TOKENS.typography.monoFamily,direction:'rtl'});box.append(label,valueNode);return box;}

function appendSpatialAuthoring(editor:HTMLElement,engineeringInput:Readonly<SimulationRunInput>,actions:Readonly<PipelineViewActions>):void{
  const section=document.createElement('section');styleEngineeringSection(section);Object.assign(section.style,{marginTop:'12px'});const previous=engineeringInput.pipeline.segments.at(-1);const previousEnd=previous?.spatial?.endPoint;appendEngineeringSectionHeader(section,'تعریف سه‌بعدی مسیر',previous?previousEnd?`قطعه جدید به انتهای ${previous.id} متصل می‌شود.`:`قطعه ${previous.id} هندسه معتبر ندارد.`:'نقطه شروع و پایان قطعه اول را وارد کنید.','مختصات سه‌بعدی');
  const body=document.createElement('div');Object.assign(body.style,{padding:'12px'});const form=document.createElement('div');Object.assign(form.style,{display:'grid',gridTemplateColumns:'repeat(2,minmax(0,1fr))',gap:'8px'});body.appendChild(form);section.appendChild(body);
  const textInput=(labelText:string,value='')=>{const label=document.createElement('label');const span=document.createElement('span');span.textContent=labelText;const input=document.createElement('input');input.value=value;styleEngineeringField(label,input,span);label.append(span,input);form.appendChild(label);return input;};const numberInput=(labelText:string,value='')=>{const input=textInput(labelText,value);input.type='number';input.step='any';return input;};
  const id=textInput('شناسه قطعه');const radius=numberInput('شعاع داخلی لوله · متر');let sx:HTMLInputElement|null=null,sy:HTMLInputElement|null=null,sz:HTMLInputElement|null=null;if(!previous){sx=numberInput('مختصات شروع X · متر');sy=numberInput('مختصات شروع Y · متر');sz=numberInput('مختصات شروع Z · متر');}else if(previousEnd){const start=document.createElement('div');start.style.gridColumn='1 / -1';start.appendChild(derivedValue(`نقطه شروع · متصل به ${previous.id}`,`(${previousEnd.xM}, ${previousEnd.yM}, ${previousEnd.zM}) متر`));form.appendChild(start);}const ex=numberInput('مختصات پایان X · متر');const ey=numberInput('مختصات پایان Y · متر');const ez=numberInput('مختصات پایان Z · متر');const error=document.createElement('small');Object.assign(error.style,{gridColumn:'1 / -1',minHeight:'1.2em',color:TOLUE_DESIGN_TOKENS.color.statusCritical});const add=document.createElement('button');add.type='button';add.textContent='افزودن قطعه مستقیم';styleEngineeringButton(add,true);add.style.gridColumn='1 / -1';add.disabled=Boolean(previous&&!previousEnd);add.addEventListener('click',()=>{try{if(id.value.trim()==='')throw new Error('شناسه قطعه الزامی است.');const startPoint=previousEnd?undefined:{xM:requiredNumber(sx,'مختصات X شروع الزامی است.'),yM:requiredNumber(sy,'مختصات Y شروع الزامی است.'),zM:requiredNumber(sz,'مختصات Z شروع الزامی است.')};actions.updateInput(appendStraightSpatialSegmentDraft(engineeringInput,{id:id.value,pipeRadiusM:requiredNumber(radius,'شعاع داخلی لوله الزامی است.'),...(startPoint?{startPoint}:{}),endPoint:{xM:requiredNumber(ex,'مختصات X پایان الزامی است.'),yM:requiredNumber(ey,'مختصات Y پایان الزامی است.'),zM:requiredNumber(ez,'مختصات Z پایان الزامی است.')}}));error.textContent='';}catch(err){error.textContent=err instanceof Error?err.message:'خطای نامشخص در تعریف مسیر';}});form.append(error,add);editor.appendChild(section);
}

export function renderPipelineView(root:HTMLElement,presentation:Readonly<PipelinePresentation>=EMPTY_PIPELINE,pressureProfile?:Readonly<PressureProfilePresentation>,pressureComposition?:Readonly<PressureCompositionPresentation>,engineeringInput?:Readonly<SimulationRunInput>|null,actions?:Readonly<PipelineViewActions>,options:Readonly<PipelineViewOptions>={}):void{
  root.replaceChildren();
  if(engineeringInput&&actions){const editor=document.createElement('section');editor.setAttribute('aria-label','ورودی‌های مسیر');styleEngineeringSection(editor,true);Object.assign(editor.style,{marginBottom:'12px'});appendEngineeringSectionHeader(editor,'مسیر، هندسه و مشخصات جریان','ورودی‌های اصلی مسیر. هر تغییر، نتیجه تحلیل قبلی را قدیمی می‌کند.',`${engineeringInput.pipeline.segments.length} قطعه`);const body=document.createElement('div');Object.assign(body.style,{padding:'14px'});editor.appendChild(body);
    const grid=document.createElement('div');Object.assign(grid.style,{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(190px,1fr))',gap:TOLUE_DESIGN_TOKENS.spacing.md});const scalars:readonly [PipelineScalarPath,string,string][]=[['targetFlowRateM3s','دبی هدف','مترمکعب بر ثانیه'],['densityKgM3','چگالی بتن','کیلوگرم بر مترمکعب'],['lubricationLayerThicknessM','ضخامت لایه روانکار','متر']];for(const[path,label,unit]of scalars)grid.appendChild(numericEditor(`${label} · ${unit}`,engineeringInput.pipeline[path],value=>actions.updateInput(updatePipelineScalarDraft(engineeringInput,path,value))));body.appendChild(grid);renderLubricationLayerQualificationView(body,engineeringInput,actions);
    engineeringInput.pipeline.segments.forEach((segment,index)=>{if(segment.kind!=='straight')return;const selected=options.selectedSegmentId===segment.id;const block=document.createElement('section');Object.assign(block.style,{marginTop:'12px',padding:'10px',border:`1px solid ${selected?TOLUE_DESIGN_TOKENS.color.selection:TOLUE_DESIGN_TOKENS.color.border}`,borderInlineStart:selected?`4px solid ${TOLUE_DESIGN_TOKENS.color.selection}`:undefined,borderRadius:TOLUE_DESIGN_TOKENS.radius.md,background:selected?'rgba(245,155,50,.06)':'rgba(7,16,22,.5)'});const head=document.createElement('div');Object.assign(head.style,{display:'flex',justifyContent:'space-between',alignItems:'center',gap:'8px',marginBottom:'10px'});const name=document.createElement('strong');name.textContent=segment.id;name.style.direction='ltr';const meta=document.createElement('small');meta.textContent=selected?'انتخاب‌شده':segment.spatial?'سه‌بعدی':'قدیمی';Object.assign(meta.style,{color:selected?TOLUE_DESIGN_TOKENS.color.selection:segment.spatial?TOLUE_DESIGN_TOKENS.color.statusNominal:TOLUE_DESIGN_TOKENS.color.statusWarning});head.append(name,meta);block.appendChild(head);const segmentGrid=document.createElement('div');Object.assign(segmentGrid.style,{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(180px,1fr))',gap:TOLUE_DESIGN_TOKENS.spacing.md});
      if(segment.spatial){segmentGrid.append(derivedValue('طول محاسبه‌شده',`${segment.lengthM} متر`),derivedValue('اختلاف ارتفاع محاسبه‌شده',`${segment.elevationChangeM} متر`));segmentGrid.appendChild(numericEditor('شعاع داخلی · متر',segment.pipeRadiusM,value=>actions.updateInput(updateStraightSpatialSegmentDraft(engineeringInput,index,{pipeRadiusM:value}))));const start=segment.spatial.startPoint;const end=segment.spatial.endPoint;const startLocked=Boolean(segment.spatial.connectedFromSegmentId);if(startLocked)segmentGrid.appendChild(derivedValue(`نقطه شروع · ${segment.spatial.connectedFromSegmentId}`,`(${start.xM}, ${start.yM}, ${start.zM})`));else{segmentGrid.appendChild(numericEditor('شروع X · متر',start.xM,value=>actions.updateInput(updateStraightSpatialSegmentDraft(engineeringInput,index,{startPoint:{...start,xM:value}}))));segmentGrid.appendChild(numericEditor('شروع Y · متر',start.yM,value=>actions.updateInput(updateStraightSpatialSegmentDraft(engineeringInput,index,{startPoint:{...start,yM:value}}))));segmentGrid.appendChild(numericEditor('شروع Z · متر',start.zM,value=>actions.updateInput(updateStraightSpatialSegmentDraft(engineeringInput,index,{startPoint:{...start,zM:value}}))));}segmentGrid.appendChild(numericEditor('پایان X · متر',end.xM,value=>actions.updateInput(updateStraightSpatialSegmentDraft(engineeringInput,index,{endPoint:{...end,xM:value}}))));segmentGrid.appendChild(numericEditor('پایان Y · متر',end.yM,value=>actions.updateInput(updateStraightSpatialSegmentDraft(engineeringInput,index,{endPoint:{...end,yM:value}}))));segmentGrid.appendChild(numericEditor('پایان Z · متر',end.zM,value=>actions.updateInput(updateStraightSpatialSegmentDraft(engineeringInput,index,{endPoint:{...end,zM:value}}))));}
      else{const fields:readonly [StraightSegmentNumericField,string,string][]=[['lengthM','طول','متر'],['pipeRadiusM','شعاع داخلی','متر'],['elevationChangeM','تغییر ارتفاع','متر']];for(const[field,label,unit]of fields)segmentGrid.appendChild(numericEditor(`${label} · ${unit}`,segment[field],value=>actions.updateInput(updateStraightSegmentDraft(engineeringInput,index,field,value))));}block.appendChild(segmentGrid);body.appendChild(block);});appendSpatialAuthoring(body,engineeringInput,actions);root.appendChild(editor);}

  const panel=document.createElement('section');panel.setAttribute('aria-label','اجزای فشار خط لوله');styleEngineeringSection(panel);appendEngineeringSectionHeader(panel,'اجزای فشار خط لوله','فقط خروجی هسته مهندسی نمایش داده می‌شود و مقدار ناموجود با صفر جایگزین نمی‌شود.',assessmentStatusFa(presentation.completeness));const body=document.createElement('div');Object.assign(body.style,{padding:'14px'});const grid=document.createElement('div');Object.assign(grid.style,{display:'grid',gridTemplateColumns:'repeat(2,minmax(0,1fr))',gap:'8px'});for(const component of presentation.components){const card=document.createElement('article');Object.assign(card.style,{padding:'10px',background:TOLUE_DESIGN_TOKENS.color.surfaceMuted,border:`1px solid ${TOLUE_DESIGN_TOKENS.color.border}`,borderRadius:TOLUE_DESIGN_TOKENS.radius.sm});const label=document.createElement('small');label.textContent=component.label;label.style.color=TOLUE_DESIGN_TOKENS.color.textMuted;const value=document.createElement('strong');value.textContent=formatPressure(component.valuePa);Object.assign(value.style,{display:'block',marginTop:'4px',fontFamily:TOLUE_DESIGN_TOKENS.typography.monoFamily,direction:'rtl',color:component.id==='required'?TOLUE_DESIGN_TOKENS.color.statusWarning:TOLUE_DESIGN_TOKENS.color.text});card.append(label,value);grid.appendChild(card);}const meta=document.createElement('small');meta.textContent=`شناسه روش: ${presentation.method}`;Object.assign(meta.style,{display:'block',marginTop:'10px',color:TOLUE_DESIGN_TOKENS.color.textMuted,direction:'rtl'});body.append(grid,meta);panel.appendChild(body);root.appendChild(panel);renderPressureCompositionView(root,pressureComposition);renderPressureProfileView(root,pressureProfile,{selectedSegmentId:options.selectedSegmentId,onSelectSegment:actions?.selectSegment});
}
