import { TOLUE_DESIGN_TOKENS } from './designSystem';
import { appendEngineeringSectionHeader, styleEngineeringButton, styleEngineeringSection } from './engineeringPanelStyle';
import type { ReportExportPresentation } from './reportPresentation';

export type ReportExportFormat='pdf'|'html'|'json';
export interface ReportExportActions { readonly exportActiveEngineeringArtifact:(format:ReportExportFormat)=>Promise<unknown>; }
export interface PdfExportStatusPresentation { readonly status:'SUCCESS'|'CANCELLED'|'FAILED'|'REJECTED'; readonly message:string; }
function isRecord(value:unknown):value is Record<string,unknown>{return typeof value==='object'&&value!==null&&!Array.isArray(value);}
export function presentEngineeringPdfExportResponse(report:Readonly<ReportExportPresentation>,response:unknown):Readonly<PdfExportStatusPresentation>{if(!isRecord(response))throw new Error('REPORT-PDF-RESPONSE-SHAPE-001');const status=response.status;if(status!=='SUCCESS'&&status!=='CANCELLED'&&status!=='FAILED'&&status!=='REJECTED')throw new Error('REPORT-PDF-RESPONSE-STATUS-001');const errorCode=typeof response.errorCode==='string'?response.errorCode:null;if(status==='REJECTED')return Object.freeze({status,message:`درخواست صدور PDF رد شد${errorCode?` · کد خطا: ${errorCode}`:''}`});if(response.runId!==report.runId||response.engineVersion!==report.engineVersion||response.inputSnapshotHash!==report.inputSnapshotHash)throw new Error('REPORT-PDF-RESPONSE-IDENTITY-001');if(status==='CANCELLED')return Object.freeze({status,message:'صدور PDF توسط کاربر لغو شد؛ فایلی نوشته نشد.'});if(status==='FAILED')return Object.freeze({status,message:`صدور PDF انجام نشد${errorCode?` · کد خطا: ${errorCode}`:''}`});const savedFileName=typeof response.savedFileName==='string'&&response.savedFileName.trim()?response.savedFileName:null;const bytesWritten=typeof response.bytesWritten==='number'&&Number.isFinite(response.bytesWritten)&&response.bytesWritten>0?response.bytesWritten:null;if(!savedFileName||bytesWritten===null||errorCode!==null)throw new Error('REPORT-PDF-RESPONSE-SUCCESS-001');return Object.freeze({status,message:`PDF با موفقیت ذخیره شد: ${savedFileName} · ${bytesWritten.toLocaleString('fa-IR')} بایت`});}
export function presentEngineeringReportTextExportResponse(report:Readonly<ReportExportPresentation>,format:'html'|'json',response:unknown):Readonly<PdfExportStatusPresentation>{if(!isRecord(response))throw new Error('REPORT-TEXT-RESPONSE-SHAPE-001');const status=response.status;if(status!=='SUCCESS'&&status!=='CANCELLED'&&status!=='FAILED'&&status!=='REJECTED')throw new Error('REPORT-TEXT-RESPONSE-STATUS-001');const errorCode=typeof response.errorCode==='string'?response.errorCode:null;const label=format.toUpperCase();if(status==='REJECTED')return Object.freeze({status,message:`درخواست صدور ${label} رد شد${errorCode?` · کد خطا: ${errorCode}`:''}`});if(response.runId!==report.runId||response.engineVersion!==report.engineVersion||response.inputSnapshotHash!==report.inputSnapshotHash||response.format!==format)throw new Error('REPORT-TEXT-RESPONSE-IDENTITY-001');if(status==='CANCELLED')return Object.freeze({status,message:`صدور ${label} توسط کاربر لغو شد؛ فایلی نوشته نشد.`});if(status==='FAILED')return Object.freeze({status,message:`صدور ${label} انجام نشد${errorCode?` · کد خطا: ${errorCode}`:''}`});const savedFileName=typeof response.savedFileName==='string'&&response.savedFileName.trim()?response.savedFileName:null;const bytesWritten=typeof response.bytesWritten==='number'&&Number.isFinite(response.bytesWritten)&&response.bytesWritten>0?response.bytesWritten:null;if(!savedFileName||bytesWritten===null||errorCode!==null)throw new Error('REPORT-TEXT-RESPONSE-SUCCESS-001');return Object.freeze({status,message:`${label} با موفقیت ذخیره شد: ${savedFileName} · ${bytesWritten.toLocaleString('fa-IR')} بایت`});}
function appendFormatCard(root:HTMLElement,titleText:string,mediaType:string,descriptionText:string,buttonText:string,enabled:boolean):HTMLButtonElement{const card=document.createElement('article');Object.assign(card.style,{display:'grid',gridTemplateColumns:'minmax(0,1fr) auto',alignItems:'center',gap:'10px',padding:'11px 12px',background:'rgba(12,23,30,.74)',border:`1px solid ${TOLUE_DESIGN_TOKENS.color.border}`,borderRadius:TOLUE_DESIGN_TOKENS.radius.sm});const copy=document.createElement('div');const title=document.createElement('strong');title.textContent=titleText;const description=document.createElement('p');description.textContent=descriptionText;Object.assign(description.style,{margin:'5px 0',color:TOLUE_DESIGN_TOKENS.color.textMuted});const media=document.createElement('small');media.textContent=`نوع فایل: ${mediaType}`;media.style.direction='rtl';copy.append(title,description,media);const button=document.createElement('button');button.type='button';button.textContent=buttonText;button.disabled=!enabled;button.dataset.exportFormat=titleText.toLowerCase();styleEngineeringButton(button,true);Object.assign(button.style,{minWidth:'112px',whiteSpace:'nowrap'});card.append(copy,button);root.appendChild(card);return button;}
function statusColor(status:PdfExportStatusPresentation['status']):string{return status==='SUCCESS'?TOLUE_DESIGN_TOKENS.color.statusNominal:status==='FAILED'||status==='REJECTED'?TOLUE_DESIGN_TOKENS.color.statusCritical:TOLUE_DESIGN_TOKENS.color.statusWarning;}

export function renderReportView(root:HTMLElement,report?:Readonly<ReportExportPresentation>,actions?:Readonly<ReportExportActions>):void{
  const panel=document.createElement('section');panel.setAttribute('aria-label','گزارش و خروجی');styleEngineeringSection(panel,true);appendEngineeringSectionHeader(panel,'گزارش مهندسی و خروجی‌ها','هویت اجرا، نسخه موتور و Snapshot پیش از صدور کنترل می‌شوند.','گزارش');const body=document.createElement('div');body.style.padding='12px';panel.appendChild(body);
  if(!report){const empty=document.createElement('div');empty.setAttribute('role','status');empty.textContent='گزارش هنوز آماده نیست. ابتدا تحلیل معتبر را اجرا کنید.';Object.assign(empty.style,{padding:'12px',background:TOLUE_DESIGN_TOKENS.color.surfaceMuted,borderRadius:TOLUE_DESIGN_TOKENS.radius.sm,color:TOLUE_DESIGN_TOKENS.color.textMuted});body.appendChild(empty);root.appendChild(panel);return;}
  const readiness=document.createElement('div');readiness.setAttribute('role','status');readiness.textContent='آماده صدور · خروجی‌ها به اجرای فعال و Snapshot فعلی متصل هستند.';Object.assign(readiness.style,{marginBottom:'10px',padding:'9px 11px',border:`1px solid ${TOLUE_DESIGN_TOKENS.color.statusNominal}`,borderRadius:TOLUE_DESIGN_TOKENS.radius.sm,color:TOLUE_DESIGN_TOKENS.color.statusNominal,fontWeight:'700'});body.appendChild(readiness);
  const exportStatus=document.createElement('p');exportStatus.setAttribute('aria-live','polite');exportStatus.style.color=TOLUE_DESIGN_TOKENS.color.textMuted;exportStatus.style.margin='10px 0 0';
  const formats=document.createElement('div');Object.assign(formats.style,{display:'grid',gridTemplateColumns:'repeat(3,minmax(0,1fr))',gap:'8px'});const pdfButton=appendFormatCard(formats,'PDF A4',report.pdfRequest.mediaType,'گزارش یک‌برگی شامل همه نتایج، تحلیل‌ها، هشدارها، محدودیت‌ها و رهگیری اجرای فعال','ذخیره PDF A4',Boolean(actions));pdfButton.dataset.engineeringPdfExport='true';const htmlButton=appendFormatCard(formats,'HTML',report.htmlMediaType,'نمای ساخت‌یافته گزارش طبق قرارداد هسته','ذخیره HTML',Boolean(actions));const jsonButton=appendFormatCard(formats,'JSON',report.jsonMediaType,'داده ساخت‌یافته برای رهگیری و تبادل فنی','ذخیره JSON',Boolean(actions));body.append(formats,exportStatus);
  if(!actions){exportStatus.textContent='عملیات صدور فایل در این نشست در دسترس نیست.';}else{
    const buttons=[pdfButton,htmlButton,jsonButton];
    const runExport=(button:HTMLButtonElement,format:ReportExportFormat,idleText:string,busyText:string)=>{button.addEventListener('click',()=>{for(const item of buttons)item.disabled=true;button.setAttribute('aria-busy','true');button.textContent=busyText;exportStatus.textContent=`در حال آماده‌سازی و ذخیره خروجی ${format.toUpperCase()}…`;exportStatus.style.color=TOLUE_DESIGN_TOKENS.color.textMuted;void actions.exportActiveEngineeringArtifact(format).then(response=>{const presentation=format==='pdf'?presentEngineeringPdfExportResponse(report,response):presentEngineeringReportTextExportResponse(report,format,response);exportStatus.textContent=presentation.message;exportStatus.style.color=statusColor(presentation.status);}).catch(()=>{exportStatus.textContent='پاسخ صدور فایل معتبر نیست یا هویت اجرا/Hash با نشست فعال تطابق ندارد.';exportStatus.style.color=TOLUE_DESIGN_TOKENS.color.statusCritical;}).finally(()=>{for(const item of buttons)item.disabled=false;button.removeAttribute('aria-busy');button.textContent=idleText;});});};
    runExport(pdfButton,'pdf','ذخیره PDF A4','در حال ساخت A4…');
    runExport(htmlButton,'html','ذخیره HTML','در حال ذخیره HTML…');
    runExport(jsonButton,'json','ذخیره JSON','در حال ذخیره JSON…');
  }
  const traceability=document.createElement('details');traceability.style.marginTop='10px';const traceSummary=document.createElement('summary');traceSummary.textContent='هویت و رهگیری گزارش';traceSummary.style.cursor='pointer';const meta=document.createElement('div');Object.assign(meta.style,{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(180px,1fr))',gap:'8px',marginTop:'8px'});for(const [labelText,valueText] of [['شناسه اجرا',report.runId],['نسخه موتور',report.engineVersion],['اثر انگشت ورودی',report.inputSnapshotHash],['زبان گزارش',report.reportLocale],['جهت نوشتار',report.reportDirection==='rtl'?'راست‌به‌چپ':report.reportDirection],['روش بسته‌بندی',report.bundleMethod]] as const){const card=document.createElement('article');Object.assign(card.style,{padding:'8px 10px',background:TOLUE_DESIGN_TOKENS.color.surfaceMuted,borderRadius:TOLUE_DESIGN_TOKENS.radius.sm});const label=document.createElement('small');label.textContent=labelText;label.style.color=TOLUE_DESIGN_TOKENS.color.textMuted;const value=document.createElement('div');value.textContent=valueText;Object.assign(value.style,{marginTop:'3px',overflowWrap:'anywhere',direction:'ltr',fontFamily:TOLUE_DESIGN_TOKENS.typography.monoFamily,fontSize:TOLUE_DESIGN_TOKENS.typography.fontSizeXs});card.append(label,value);meta.appendChild(card);}traceability.append(traceSummary,meta);body.appendChild(traceability);
  const exportHint=document.createElement('p');exportHint.textContent='این خروجی، گزارش کامل اجرای فعال را در قالب یک برگ A4 فشرده صادر می‌کند؛ هیچ محاسبه یا استنتاج جدیدی در لایه گزارش انجام نمی‌شود. HTML و JSON نیز از همان Snapshot فعال ذخیره می‌شوند.';Object.assign(exportHint.style,{margin:'10px 0 0',paddingTop:'9px',borderTop:`1px solid ${TOLUE_DESIGN_TOKENS.color.border}`,color:TOLUE_DESIGN_TOKENS.color.textMuted});body.appendChild(exportHint);root.appendChild(panel);
}
