import type { ProvenanceActivityKind, ProvenanceEntityKind } from '../../engineering/core/inputProvenance';
import type { SimulationRunInput } from '../../engineering/core/simulationRun';
import { TOLUE_DESIGN_TOKENS } from './designSystem';
import { removeRheologyProvenanceDraft, setRheologyProvenanceDraft, updateRheologyInputDraft, type RheologyInputPath, type RheologyProvenanceField } from './engineeringInputDraft';
import type { RheologyCurvesPresentation } from './rheologyCurvePresentation';
import { createRheologyInputPresentation, type RheologyInputPresentation } from './rheologyPresentation';

const EMPTY_RHEOLOGY_INPUTS: readonly Readonly<RheologyInputPresentation>[] = Object.freeze([
  createRheologyInputPresentation({ modelFamily: 'BINGHAM', inputId: 'yield-stress', label: 'تنش تسلیم', value: null, unit: 'Pa' }),
  createRheologyInputPresentation({ modelFamily: 'BINGHAM', inputId: 'plastic-viscosity', label: 'ویسکوزیته پلاستیک', value: null, unit: 'Pa·s' }),
]);
export interface RheologyViewActions { readonly updateInput: (input: Readonly<SimulationRunInput>) => void; }
const EDITABLE_FIELDS: readonly { path: RheologyInputPath; label: string; unit: string; min: number; step: string }[] = Object.freeze([
  { path: 'bulk.yieldStressPa', label: 'تنش تسلیم بتن', unit: 'Pa', min: 0, step: 'any' },
  { path: 'bulk.plasticViscosityPaS', label: 'ویسکوزیته پلاستیک بتن', unit: 'Pa·s', min: Number.MIN_VALUE, step: 'any' },
  { path: 'lubricationLayer.yieldStressPa', label: 'تنش تسلیم لایه روانکار', unit: 'Pa', min: 0, step: 'any' },
  { path: 'lubricationLayer.plasticViscosityPaS', label: 'ویسکوزیته پلاستیک لایه روانکار', unit: 'Pa·s', min: Number.MIN_VALUE, step: 'any' },
]);
function valueAt(input: Readonly<SimulationRunInput>, path: RheologyInputPath): number { const [family,key]=path.split('.') as ['bulk'|'lubricationLayer','yieldStressPa'|'plasticViscosityPaS']; return input.pipeline[family][key]; }
function textInput(labelText:string,value=''): {wrapper:HTMLElement;input:HTMLInputElement} { const wrapper=document.createElement('label');wrapper.style.display='grid';wrapper.style.gap=TOLUE_DESIGN_TOKENS.spacing.xs;const label=document.createElement('span');label.textContent=labelText;const input=document.createElement('input');input.type='text';input.value=value;input.style.padding=TOLUE_DESIGN_TOKENS.spacing.sm;input.style.border=`1px solid ${TOLUE_DESIGN_TOKENS.color.border}`;input.style.borderRadius=TOLUE_DESIGN_TOKENS.radius.sm;input.style.fontFamily='inherit';wrapper.append(label,input);return{wrapper,input}; }
function provenanceEditor(input:Readonly<SimulationRunInput>,field:RheologyProvenanceField,titleText:string,actions:Readonly<RheologyViewActions>):HTMLElement {
  const existing=input.provenance?.[field]; const box=document.createElement('section');box.style.marginTop=TOLUE_DESIGN_TOKENS.spacing.lg;box.style.padding=TOLUE_DESIGN_TOKENS.spacing.md;box.style.border=`1px solid ${TOLUE_DESIGN_TOKENS.color.border}`;box.style.borderRadius=TOLUE_DESIGN_TOKENS.radius.sm;
  const title=document.createElement('h3');title.textContent=`منشأ رئولوژی — ${titleText}`;title.style.marginTop='0';
  const status=document.createElement('small');status.textContent=existing?`ثبت شده: ${existing.evidence.entityKind}`:'هنوز provenance ثبت نشده است.';status.style.color=TOLUE_DESIGN_TOKENS.color.textMuted;box.append(title,status);
  const grid=document.createElement('div');grid.style.display='grid';grid.style.gridTemplateColumns='repeat(auto-fit,minmax(180px,1fr))';grid.style.gap=TOLUE_DESIGN_TOKENS.spacing.sm;grid.style.marginTop=TOLUE_DESIGN_TOKENS.spacing.md;
  const entityId=textInput('Entity ID',existing?.evidence.entityId??''); const activityId=textInput('Activity ID',existing?.evidence.generatedByActivityId??''); const methodId=textInput('Method / procedure ID',existing?.activities[0]?.methodId??''); const equipmentId=textInput('Equipment ID',existing?.agents.find(a=>a.kind==='equipment')?.id??''); const equipmentLabel=textInput('Equipment label',existing?.agents.find(a=>a.kind==='equipment')?.label??''); const sourceDocumentId=textInput('Source document ID',existing?.evidence.sourceDocumentId??''); const referenceId=textInput('Reference ID',existing?.evidence.referenceIds?.[0]??''); const note=textInput('Note',existing?.evidence.note??'');
  const entityKindWrap=document.createElement('label');entityKindWrap.textContent='نوع داده';entityKindWrap.style.display='grid';entityKindWrap.style.gap=TOLUE_DESIGN_TOKENS.spacing.xs;const entityKind=document.createElement('select');(['measurement_result','derived_result','engineering_assumption'] as ProvenanceEntityKind[]).forEach(v=>{const o=document.createElement('option');o.value=v;o.textContent=v;o.selected=existing?.evidence.entityKind===v;entityKind.appendChild(o);});entityKindWrap.appendChild(entityKind);
  const activityKindWrap=document.createElement('label');activityKindWrap.textContent='نوع فعالیت';activityKindWrap.style.display='grid';activityKindWrap.style.gap=TOLUE_DESIGN_TOKENS.spacing.xs;const activityKind=document.createElement('select');(['measurement','calibration','derivation','assumption'] as ProvenanceActivityKind[]).forEach(v=>{const o=document.createElement('option');o.value=v;o.textContent=v;o.selected=existing?.activities[0]?.kind===v;activityKind.appendChild(o);});activityKindWrap.appendChild(activityKind);
  [entityId.wrapper,entityKindWrap,activityId.wrapper,activityKindWrap,methodId.wrapper,equipmentId.wrapper,equipmentLabel.wrapper,sourceDocumentId.wrapper,referenceId.wrapper,note.wrapper].forEach(x=>grid.appendChild(x));box.appendChild(grid);
  const controls=document.createElement('div');controls.style.display='flex';controls.style.gap=TOLUE_DESIGN_TOKENS.spacing.sm;controls.style.marginTop=TOLUE_DESIGN_TOKENS.spacing.md;const save=document.createElement('button');save.type='button';save.textContent='ثبت provenance';const remove=document.createElement('button');remove.type='button';remove.textContent='حذف provenance';remove.disabled=!existing;const feedback=document.createElement('small');feedback.style.alignSelf='center';
  save.addEventListener('click',()=>{try{actions.updateInput(setRheologyProvenanceDraft(input,field,{entityId:entityId.input.value,entityKind:entityKind.value as ProvenanceEntityKind,activityId:activityId.input.value,activityKind:activityKind.value as ProvenanceActivityKind,methodId:methodId.input.value,equipmentId:equipmentId.input.value,equipmentLabel:equipmentLabel.input.value,sourceDocumentId:sourceDocumentId.input.value,referenceId:referenceId.input.value,note:note.input.value}));}catch{feedback.textContent='Entity ID و Activity ID الزامی و معتبر هستند.';feedback.style.color=TOLUE_DESIGN_TOKENS.color.statusCritical;}});remove.addEventListener('click',()=>actions.updateInput(removeRheologyProvenanceDraft(input,field)));controls.append(save,remove,feedback);box.appendChild(controls);return box;
}

export function renderRheologyView(root: HTMLElement, inputs: readonly Readonly<RheologyInputPresentation>[] = EMPTY_RHEOLOGY_INPUTS, curves?: Readonly<RheologyCurvesPresentation>, engineeringInput?: Readonly<SimulationRunInput> | null, actions?: Readonly<RheologyViewActions>): void {
  const panel=document.createElement('section'); panel.setAttribute('aria-label','ورودی‌های رئولوژی'); panel.style.padding=TOLUE_DESIGN_TOKENS.spacing.lg; panel.style.background=TOLUE_DESIGN_TOKENS.color.surface; panel.style.border=`1px solid ${TOLUE_DESIGN_TOKENS.color.border}`; panel.style.borderRadius=TOLUE_DESIGN_TOKENS.radius.md;
  const title=document.createElement('h2'); title.textContent='داده‌ها و منحنی‌های رئولوژی'; title.style.marginTop='0'; const note=document.createElement('p'); note.textContent='مقادیر و provenance مستقل ثبت می‌شوند. نبود provenance هیچ‌وقت با داده ساختگی پر نمی‌شود و Readiness آن را Preliminary نگه می‌دارد.'; note.style.color=TOLUE_DESIGN_TOKENS.color.textMuted; panel.append(title,note);
  if (engineeringInput && actions) {
    const form=document.createElement('div'); form.style.display='grid'; form.style.gridTemplateColumns='repeat(auto-fit, minmax(220px, 1fr))'; form.style.gap=TOLUE_DESIGN_TOKENS.spacing.md; form.dataset.engineeringInput='rheology';
    for (const field of EDITABLE_FIELDS) { const wrapper=document.createElement('label');wrapper.style.display='grid';wrapper.style.gap=TOLUE_DESIGN_TOKENS.spacing.sm;const caption=document.createElement('span');caption.textContent=`${field.label} (${field.unit})`;const control=document.createElement('input');control.type='number';control.step=field.step;control.min=String(field.min);control.value=String(valueAt(engineeringInput,field.path));control.dataset.inputPath=field.path;control.style.fontFamily='inherit';control.style.padding=TOLUE_DESIGN_TOKENS.spacing.md;control.style.border=`1px solid ${TOLUE_DESIGN_TOKENS.color.border}`;control.style.borderRadius=TOLUE_DESIGN_TOKENS.radius.sm;const feedback=document.createElement('small');feedback.style.minHeight='1.2em';feedback.style.color=TOLUE_DESIGN_TOKENS.color.statusCritical;control.addEventListener('change',()=>{try{actions.updateInput(updateRheologyInputDraft(engineeringInput,field.path,Number(control.value)));}catch{feedback.textContent='مقدار واردشده معتبر نیست.';}});wrapper.append(caption,control,feedback);form.appendChild(wrapper); }
    panel.appendChild(form); panel.append(provenanceEditor(engineeringInput,'bulkRheology','بتن',actions),provenanceEditor(engineeringInput,'lubricationLayerRheology','لایه روانکار',actions));
  } else { const grid=document.createElement('div');grid.style.display='grid';grid.style.gridTemplateColumns='repeat(auto-fit,minmax(220px,1fr))';grid.style.gap=TOLUE_DESIGN_TOKENS.spacing.md;for(const input of inputs){const card=document.createElement('article');card.style.padding=TOLUE_DESIGN_TOKENS.spacing.md;card.style.background=TOLUE_DESIGN_TOKENS.color.surfaceMuted;const label=document.createElement('strong');label.textContent=input.label;const value=document.createElement('div');value.textContent=input.value===null?`— ${input.unit}`:`${input.value} ${input.unit}`;card.append(label,value);grid.appendChild(card);}panel.appendChild(grid); }
  if(curves){const chart=document.createElementNS('http://www.w3.org/2000/svg','svg');chart.setAttribute('viewBox','0 0 640 320');chart.style.width='100%';chart.style.marginTop=TOLUE_DESIGN_TOKENS.spacing.lg;const all=curves.series.flatMap(s=>s.points);const maxX=Math.max(...all.map(p=>p.shearRateSInv),1);const maxY=Math.max(...all.map(p=>p.shearStressPa),1);const sx=(x:number)=>40+(x/maxX)*560;const sy=(y:number)=>280-(y/maxY)*240;curves.series.forEach((s,i)=>{const poly=document.createElementNS('http://www.w3.org/2000/svg','polyline');poly.setAttribute('fill','none');poly.setAttribute('stroke','currentColor');poly.setAttribute('stroke-width',i===0?'3':'2');poly.setAttribute('stroke-dasharray',i===0?'':'8 6');poly.setAttribute('points',s.points.map(p=>`${sx(p.shearRateSInv)},${sy(p.shearStressPa)}`).join(' '));chart.appendChild(poly);});panel.appendChild(chart);} else {const empty=document.createElement('p');empty.textContent='هنوز منحنی رئولوژی معتبر از تحلیل فعال دریافت نشده است.';panel.appendChild(empty);}root.appendChild(panel);
}
