import type { ProvenanceActivityKind, ProvenanceEntityKind } from '../../engineering/core/inputProvenance';
import type { SimulationRunInput } from '../../engineering/core/simulationRun';
import { TOLUE_DESIGN_TOKENS } from './designSystem';
import { appendEngineeringSectionHeader, styleEngineeringButton, styleEngineeringField, styleEngineeringSection } from './engineeringPanelStyle';
import { removeRheologyProvenanceDraft, setRheologyProvenanceDraft, updateRheologyInputDraft, type RheologyInputPath, type RheologyProvenanceField } from './engineeringInputDraft';
import type { RheologyCurvesPresentation } from './rheologyCurvePresentation';
import { createRheologyInputPresentation, type RheologyInputPresentation } from './rheologyPresentation';

const EMPTY_RHEOLOGY_INPUTS: readonly Readonly<RheologyInputPresentation>[] = Object.freeze([
  createRheologyInputPresentation({ modelFamily: 'BINGHAM', inputId: 'yield-stress', label: 'تنش تسلیم', value: null, unit: 'Pa' }),
  createRheologyInputPresentation({ modelFamily: 'BINGHAM', inputId: 'plastic-viscosity', label: 'ویسکوزیته پلاستیک', value: null, unit: 'Pa·s' }),
]);
export interface RheologyViewActions { readonly updateInput: (input: Readonly<SimulationRunInput>) => void; }
const EDITABLE_FIELDS: readonly { path: RheologyInputPath; label: string; unit: string; min: number; step: string; family:'bulk'|'ll' }[] = Object.freeze([
  { path: 'bulk.yieldStressPa', label: 'تنش تسلیم بتن', unit: 'Pa', min: 0, step: 'any', family:'bulk' },
  { path: 'bulk.plasticViscosityPaS', label: 'ویسکوزیته پلاستیک بتن', unit: 'Pa·s', min: Number.MIN_VALUE, step: 'any', family:'bulk' },
  { path: 'lubricationLayer.yieldStressPa', label: 'تنش تسلیم لایه روانکار', unit: 'Pa', min: 0, step: 'any', family:'ll' },
  { path: 'lubricationLayer.plasticViscosityPaS', label: 'ویسکوزیته پلاستیک لایه روانکار', unit: 'Pa·s', min: Number.MIN_VALUE, step: 'any', family:'ll' },
]);
function valueAt(input: Readonly<SimulationRunInput>, path: RheologyInputPath): number { const [family,key]=path.split('.') as ['bulk'|'lubricationLayer','yieldStressPa'|'plasticViscosityPaS']; return input.pipeline[family][key]; }
function textInput(labelText:string,value=''): {wrapper:HTMLLabelElement;input:HTMLInputElement} { const wrapper=document.createElement('label');const label=document.createElement('span');label.textContent=labelText;const input=document.createElement('input');input.type='text';input.value=value;styleEngineeringField(wrapper,input,label);wrapper.append(label,input);return{wrapper,input}; }
function provenanceEditor(input:Readonly<SimulationRunInput>,field:RheologyProvenanceField,titleText:string,actions:Readonly<RheologyViewActions>):HTMLElement {
  const existing=input.provenance?.[field]; const box=document.createElement('section');styleEngineeringSection(box);Object.assign(box.style,{marginTop:TOLUE_DESIGN_TOKENS.spacing.md});
  appendEngineeringSectionHeader(box,`منشأ رئولوژی — ${titleText}`,'ثبت منشأ، روش، تجهیز و سند منبع برای قابلیت ردیابی مهندسی.',existing?'DOCUMENTED':'MISSING');
  const body=document.createElement('div');Object.assign(body.style,{padding:'12px 14px'});
  const status=document.createElement('small');status.textContent=existing?`ثبت شده · ${existing.evidence.entityKind}`:'هنوز provenance ثبت نشده است.';status.style.color=existing?TOLUE_DESIGN_TOKENS.color.statusNominal:TOLUE_DESIGN_TOKENS.color.statusWarning;body.appendChild(status);
  const grid=document.createElement('div');Object.assign(grid.style,{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(180px,1fr))',gap:TOLUE_DESIGN_TOKENS.spacing.sm,marginTop:TOLUE_DESIGN_TOKENS.spacing.md});
  const entityId=textInput('Entity ID',existing?.evidence.entityId??''); const activityId=textInput('Activity ID',existing?.evidence.generatedByActivityId??''); const methodId=textInput('Method / procedure ID',existing?.activities[0]?.methodId??''); const equipmentId=textInput('Equipment ID',existing?.agents.find(a=>a.kind==='equipment')?.id??''); const equipmentLabel=textInput('Equipment label',existing?.agents.find(a=>a.kind==='equipment')?.label??''); const sourceDocumentId=textInput('Source document ID',existing?.evidence.sourceDocumentId??''); const referenceId=textInput('Reference ID',existing?.evidence.referenceIds?.[0]??''); const note=textInput('Note',existing?.evidence.note??'');
  const entityKindWrap=document.createElement('label');const entityKindCaption=document.createElement('span');entityKindCaption.textContent='نوع داده';const entityKind=document.createElement('select');(['measurement_result','derived_result','engineering_assumption'] as ProvenanceEntityKind[]).forEach(v=>{const o=document.createElement('option');o.value=v;o.textContent=v;o.selected=existing?.evidence.entityKind===v;entityKind.appendChild(o);});styleEngineeringField(entityKindWrap,entityKind,entityKindCaption);entityKindWrap.append(entityKindCaption,entityKind);
  const activityKindWrap=document.createElement('label');const activityKindCaption=document.createElement('span');activityKindCaption.textContent='نوع فعالیت';const activityKind=document.createElement('select');(['measurement','calibration','derivation','assumption'] as ProvenanceActivityKind[]).forEach(v=>{const o=document.createElement('option');o.value=v;o.textContent=v;o.selected=existing?.activities[0]?.kind===v;activityKind.appendChild(o);});styleEngineeringField(activityKindWrap,activityKind,activityKindCaption);activityKindWrap.append(activityKindCaption,activityKind);
  [entityId.wrapper,entityKindWrap,activityId.wrapper,activityKindWrap,methodId.wrapper,equipmentId.wrapper,equipmentLabel.wrapper,sourceDocumentId.wrapper,referenceId.wrapper,note.wrapper].forEach(x=>grid.appendChild(x));body.appendChild(grid);
  const controls=document.createElement('div');Object.assign(controls.style,{display:'flex',flexWrap:'wrap',gap:TOLUE_DESIGN_TOKENS.spacing.sm,marginTop:TOLUE_DESIGN_TOKENS.spacing.md});const save=document.createElement('button');save.type='button';save.textContent='ثبت provenance';styleEngineeringButton(save,true);const remove=document.createElement('button');remove.type='button';remove.textContent='حذف provenance';remove.disabled=!existing;styleEngineeringButton(remove,false,true);const feedback=document.createElement('small');feedback.style.alignSelf='center';
  save.addEventListener('click',()=>{try{actions.updateInput(setRheologyProvenanceDraft(input,field,{entityId:entityId.input.value,entityKind:entityKind.value as ProvenanceEntityKind,activityId:activityId.input.value,activityKind:activityKind.value as ProvenanceActivityKind,methodId:methodId.input.value,equipmentId:equipmentId.input.value,equipmentLabel:equipmentLabel.input.value,sourceDocumentId:sourceDocumentId.input.value,referenceId:referenceId.input.value,note:note.input.value}));}catch{feedback.textContent='Entity ID و Activity ID الزامی و معتبر هستند.';feedback.style.color=TOLUE_DESIGN_TOKENS.color.statusCritical;}});remove.addEventListener('click',()=>actions.updateInput(removeRheologyProvenanceDraft(input,field)));controls.append(save,remove,feedback);body.appendChild(controls);box.appendChild(body);return box;
}

export function renderRheologyView(root: HTMLElement, inputs: readonly Readonly<RheologyInputPresentation>[] = EMPTY_RHEOLOGY_INPUTS, curves?: Readonly<RheologyCurvesPresentation>, engineeringInput?: Readonly<SimulationRunInput> | null, actions?: Readonly<RheologyViewActions>): void {
  root.replaceChildren();
  const panel=document.createElement('section');panel.setAttribute('aria-label','ورودی‌های رئولوژی');styleEngineeringSection(panel,true);appendEngineeringSectionHeader(panel,'رئولوژی بتن و لایه روانکار','پارامترهای Bingham، provenance و منحنی‌های حاصل از Engineering Core.','BINGHAM');
  const body=document.createElement('div');Object.assign(body.style,{padding:'14px'});panel.appendChild(body);
  if (engineeringInput && actions) {
    const groups:readonly ['bulk'|'ll',string,string][]=[['bulk','بتن','Bulk concrete'],['ll','لایه روانکار','Lubrication layer']];
    for(const [family,titleText,tag] of groups){const group=document.createElement('section');Object.assign(group.style,{padding:'12px',marginBottom:'10px',border:`1px solid ${TOLUE_DESIGN_TOKENS.color.border}`,borderRadius:TOLUE_DESIGN_TOKENS.radius.md,background:'rgba(11,17,22,.46)'});const heading=document.createElement('div');Object.assign(heading.style,{display:'flex',justifyContent:'space-between',gap:'8px',alignItems:'center',marginBottom:'10px'});const strong=document.createElement('strong');strong.textContent=titleText;const badge=document.createElement('small');badge.textContent=tag;Object.assign(badge.style,{direction:'ltr',color:TOLUE_DESIGN_TOKENS.color.info});heading.append(strong,badge);group.appendChild(heading);const form=document.createElement('div');Object.assign(form.style,{display:'grid',gridTemplateColumns:'repeat(2,minmax(0,1fr))',gap:TOLUE_DESIGN_TOKENS.spacing.md});for (const field of EDITABLE_FIELDS.filter(item=>item.family===family)) { const wrapper=document.createElement('label');const caption=document.createElement('span');caption.textContent=`${field.label} · ${field.unit}`;const control=document.createElement('input');control.type='number';control.step=field.step;control.min=String(field.min);control.value=String(valueAt(engineeringInput,field.path));control.dataset.inputPath=field.path;styleEngineeringField(wrapper,control,caption);const feedback=document.createElement('small');feedback.style.minHeight='1.2em';feedback.style.color=TOLUE_DESIGN_TOKENS.color.statusCritical;control.addEventListener('change',()=>{try{actions.updateInput(updateRheologyInputDraft(engineeringInput,field.path,Number(control.value)));feedback.textContent='';}catch{feedback.textContent='مقدار واردشده معتبر نیست.';}});wrapper.append(caption,control,feedback);form.appendChild(wrapper);}group.appendChild(form);body.appendChild(group);}
    body.append(provenanceEditor(engineeringInput,'bulkRheology','بتن',actions),provenanceEditor(engineeringInput,'lubricationLayerRheology','لایه روانکار',actions));
  } else { const grid=document.createElement('div');Object.assign(grid.style,{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(180px,1fr))',gap:TOLUE_DESIGN_TOKENS.spacing.md});for(const input of inputs){const card=document.createElement('article');Object.assign(card.style,{padding:'12px',background:TOLUE_DESIGN_TOKENS.color.surfaceMuted,border:`1px solid ${TOLUE_DESIGN_TOKENS.color.border}`,borderRadius:TOLUE_DESIGN_TOKENS.radius.md});const label=document.createElement('small');label.textContent=input.label;label.style.color=TOLUE_DESIGN_TOKENS.color.textMuted;const value=document.createElement('strong');value.textContent=input.value===null?`— ${input.unit}`:`${input.value} ${input.unit}`;Object.assign(value.style,{display:'block',marginTop:'4px',fontFamily:TOLUE_DESIGN_TOKENS.typography.monoFamily,direction:'ltr'});card.append(label,value);grid.appendChild(card);}body.appendChild(grid); }
  const chartCard=document.createElement('section');Object.assign(chartCard.style,{marginTop:'12px',padding:'12px',border:`1px solid ${TOLUE_DESIGN_TOKENS.color.border}`,borderRadius:TOLUE_DESIGN_TOKENS.radius.md,background:'rgba(7,16,22,.66)'});const chartTitle=document.createElement('div');chartTitle.textContent='Shear stress response';Object.assign(chartTitle.style,{fontSize:TOLUE_DESIGN_TOKENS.typography.fontSizeXs,color:TOLUE_DESIGN_TOKENS.color.textMuted,direction:'ltr'});chartCard.appendChild(chartTitle);
  if(curves){const chart=document.createElementNS('http://www.w3.org/2000/svg','svg');chart.setAttribute('viewBox','0 0 640 320');chart.style.width='100%';chart.style.marginTop=TOLUE_DESIGN_TOKENS.spacing.sm;const all=curves.series.flatMap(s=>s.points);const maxX=Math.max(...all.map(p=>p.shearRateSInv),1);const maxY=Math.max(...all.map(p=>p.shearStressPa),1);const sx=(x:number)=>40+(x/maxX)*560;const sy=(y:number)=>280-(y/maxY)*240;curves.series.forEach((s,i)=>{const poly=document.createElementNS('http://www.w3.org/2000/svg','polyline');poly.setAttribute('fill','none');poly.setAttribute('stroke',i===0?TOLUE_DESIGN_TOKENS.color.info:TOLUE_DESIGN_TOKENS.color.selection);poly.setAttribute('stroke-width',i===0?'3':'2');poly.setAttribute('stroke-dasharray',i===0?'':'8 6');poly.setAttribute('points',s.points.map(p=>`${sx(p.shearRateSInv)},${sy(p.shearStressPa)}`).join(' '));chart.appendChild(poly);});chartCard.appendChild(chart);} else {const empty=document.createElement('p');empty.textContent='پس از اجرای تحلیل، منحنی معتبر Engineering Core در این بخش نمایش داده می‌شود.';empty.style.color=TOLUE_DESIGN_TOKENS.color.textMuted;chartCard.appendChild(empty);}body.appendChild(chartCard);root.appendChild(panel);
}
