import type { EngineeringRunHistoryItem } from '../main/persistence/engineeringRunRepository';
import { TOLUE_DESIGN_TOKENS } from './designSystem';
import { appendEngineeringSectionHeader, styleEngineeringButton, styleEngineeringSection } from './engineeringPanelStyle';
import { canCompareSelectedRuns, clearRunHistoryComparisonSelection, createRunHistoryComparisonSelection, runHistorySelectionSummary, selectRunForComparison } from './runHistorySelection';

export interface RunHistoryViewActions { readonly loadRun:(runId:string)=>Promise<void>; readonly compareRuns?:(baselineRunId:string,candidateRunId:string)=>Promise<void>; }
function executionStatusLabel(status:EngineeringRunHistoryItem['executionStatus']):string{return status==='EXECUTED'?'اجراشده':status==='BLOCKED'?'مسدودشده':status;}
function completenessLabel(completeness:EngineeringRunHistoryItem['completeness']):string{return completeness==='complete'?'کامل':'ناقص';}

export function renderRunHistoryView(root:HTMLElement,items:readonly Readonly<EngineeringRunHistoryItem>[],actions:Readonly<RunHistoryViewActions>):void{
  root.replaceChildren();const panel=document.createElement('section');styleEngineeringSection(panel,true);appendEngineeringSectionHeader(panel,'تاریخچه و مقایسه Runها','Run ذخیره‌شده را باز کنید یا دو Run را بدون اجرای تحلیل جدید مقایسه کنید.','RUN HISTORY');const body=document.createElement('div');body.style.padding='12px';panel.appendChild(body);
  if(!items.length){const empty=document.createElement('div');empty.textContent='هنوز تحلیل ذخیره‌شده‌ای وجود ندارد.';Object.assign(empty.style,{padding:'12px',background:TOLUE_DESIGN_TOKENS.color.surfaceMuted,borderRadius:TOLUE_DESIGN_TOKENS.radius.sm,color:TOLUE_DESIGN_TOKENS.color.textMuted});body.appendChild(empty);root.appendChild(panel);return;}
  let selectionState=createRunHistoryComparisonSelection();const toolbar=document.createElement('section');Object.assign(toolbar.style,{display:'grid',gap:'8px',padding:'10px 12px',marginBottom:'10px',background:'rgba(36,152,197,.06)',border:`1px solid ${TOLUE_DESIGN_TOKENS.color.borderStrong}`,borderRadius:TOLUE_DESIGN_TOKENS.radius.sm});const selection=document.createElement('strong');selection.setAttribute('aria-live','polite');const actionsRow=document.createElement('div');Object.assign(actionsRow.style,{display:'flex',flexWrap:'wrap',gap:'8px'});const compare=document.createElement('button');compare.type='button';compare.textContent='مقایسه تحلیل‌های انتخاب‌شده';styleEngineeringButton(compare,true);const clear=document.createElement('button');clear.type='button';clear.textContent='پاک‌کردن انتخاب‌ها';styleEngineeringButton(clear);const refresh=()=>{selection.textContent=runHistorySelectionSummary(selectionState);compare.disabled=!actions.compareRuns||!canCompareSelectedRuns(selectionState);clear.disabled=selectionState.baselineRunId===null&&selectionState.candidateRunId===null;};compare.addEventListener('click',()=>{if(actions.compareRuns&&canCompareSelectedRuns(selectionState))void actions.compareRuns(selectionState.baselineRunId!,selectionState.candidateRunId!);});clear.addEventListener('click',()=>{selectionState=clearRunHistoryComparisonSelection(selectionState);refresh();});actionsRow.append(compare,clear);toolbar.append(selection,actionsRow);refresh();body.appendChild(toolbar);
  const list=document.createElement('div');Object.assign(list.style,{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(280px,1fr))',gap:'9px'});for(const item of items){const card=document.createElement('article');Object.assign(card.style,{padding:'10px 12px',background:'rgba(12,23,30,.74)',border:`1px solid ${TOLUE_DESIGN_TOKENS.color.border}`,borderRadius:TOLUE_DESIGN_TOKENS.radius.sm});const heading=document.createElement('strong');heading.textContent=item.runId;Object.assign(heading.style,{display:'block',direction:'ltr',fontFamily:TOLUE_DESIGN_TOKENS.typography.monoFamily,overflowWrap:'anywhere'});const meta=document.createElement('p');meta.textContent=`${item.createdAtIso} · ${executionStatusLabel(item.executionStatus)} · ${completenessLabel(item.completeness)}`;Object.assign(meta.style,{color:TOLUE_DESIGN_TOKENS.color.textMuted,fontSize:TOLUE_DESIGN_TOKENS.typography.fontSizeXs,direction:'ltr'});const row=document.createElement('div');Object.assign(row.style,{display:'flex',flexWrap:'wrap',gap:'6px'});const open=document.createElement('button');open.type='button';open.textContent='بازکردن تحلیل';styleEngineeringButton(open,true);open.addEventListener('click',()=>void actions.loadRun(item.runId));const baseline=document.createElement('button');baseline.type='button';baseline.textContent='مبنا';styleEngineeringButton(baseline);baseline.addEventListener('click',()=>{selectionState=selectRunForComparison(selectionState,'baseline',item.runId);refresh();});const candidate=document.createElement('button');candidate.type='button';candidate.textContent='کاندید';styleEngineeringButton(candidate);candidate.addEventListener('click',()=>{selectionState=selectRunForComparison(selectionState,'candidate',item.runId);refresh();});row.append(open,baseline,candidate);card.append(heading,meta,row);list.appendChild(card);}body.appendChild(list);root.appendChild(panel);
}
