import { TOLUE_DESIGN_TOKENS } from './designSystem';
import type { Visualization3DPresentation } from './visualization3dPresentation';

function pressure(value: number | null): string { return value === null ? '—' : `${(value / 1_000_000).toFixed(3)} MPa`; }

export function renderVisualization3DView(root: HTMLElement, data?: Readonly<Visualization3DPresentation>): void {
  const panel = document.createElement('section'); panel.setAttribute('aria-label', 'نمایش سه‌بعدی مهندسی'); panel.style.padding=TOLUE_DESIGN_TOKENS.spacing.lg; panel.style.background=TOLUE_DESIGN_TOKENS.color.surface; panel.style.border=`1px solid ${TOLUE_DESIGN_TOKENS.color.border}`; panel.style.borderRadius=TOLUE_DESIGN_TOKENS.radius.md;
  const title=document.createElement('h2'); title.textContent='نمایش مهندسی مسیر'; title.style.marginTop='0';
  const note=document.createElement('p'); note.textContent='این نما صرفاً Engineering Visualization است و شبیه‌سازی CFD/DEM یا ادعای Physical Simulation نیست. هندسه و مقادیر فقط از قرارداد Core نمایش داده می‌شوند.'; note.style.color=TOLUE_DESIGN_TOKENS.color.textMuted; panel.append(title,note);
  if(!data){const empty=document.createElement('p');empty.textContent='هنوز داده معتبر Visualization از Engineering Core دریافت نشده است.';panel.appendChild(empty);root.appendChild(panel);return;}
  const canvas=document.createElement('div'); canvas.style.position='relative'; canvas.style.minHeight='260px'; canvas.style.overflow='auto'; canvas.style.padding=TOLUE_DESIGN_TOKENS.spacing.lg; canvas.style.background=TOLUE_DESIGN_TOKENS.color.surfaceMuted; canvas.style.border=`1px solid ${TOLUE_DESIGN_TOKENS.color.border}`; canvas.style.borderRadius=TOLUE_DESIGN_TOKENS.radius.sm;
  const route=document.createElement('div'); route.style.display='flex'; route.style.alignItems='center'; route.style.gap=TOLUE_DESIGN_TOKENS.spacing.sm; route.style.minWidth='max-content'; route.style.padding='70px 10px';
  for(const segment of data.segments){const item=document.createElement('article'); item.style.minWidth='150px'; item.style.padding=TOLUE_DESIGN_TOKENS.spacing.md; item.style.background=TOLUE_DESIGN_TOKENS.color.surface; item.style.border=`2px solid ${segment.hydraulicStatus==='computed'?TOLUE_DESIGN_TOKENS.color.focus:TOLUE_DESIGN_TOKENS.color.statusWarning}`; item.style.borderRadius=TOLUE_DESIGN_TOKENS.radius.md; item.style.transform=`translateY(${-segment.endElevationM * 2}px)`; item.dataset.segmentId=segment.id; const name=document.createElement('strong');name.textContent=`${segment.id} · ${segment.kind}`; const p=document.createElement('small');p.style.display='block';p.style.marginTop=TOLUE_DESIGN_TOKENS.spacing.sm;p.textContent=`ΔP: ${pressure(segment.totalPressureChangePa.value)}`; const remain=document.createElement('small');remain.style.display='block';remain.textContent=`P باقی‌مانده: ${pressure(segment.outletRemainingPressurePa.value)}`; const state=document.createElement('small');state.style.display='block';state.textContent=`Hydraulic: ${segment.hydraulicStatus}`;item.append(name,p,remain,state);route.appendChild(item);}
  canvas.appendChild(route); panel.appendChild(canvas);
  const meta=document.createElement('p');meta.textContent=`Representation: ${data.representation} · Physical simulation claim: ${String(data.physicalSimulationClaim)} · Completeness: ${data.completeness} · Method: ${data.method}`;meta.style.color=TOLUE_DESIGN_TOKENS.color.textMuted;panel.appendChild(meta);
  if(data.warnings.length){const warnings=document.createElement('ul');for(const warning of data.warnings){const li=document.createElement('li');li.textContent=warning;warnings.appendChild(li);}panel.appendChild(warnings);} root.appendChild(panel);
}
