import type { EngineeringAnalysisResult } from '../../../engineering/core/engineeringAnalysis';
import type { SimulationRunInput } from '../../../engineering/core/simulationRun';

export interface PersistedEngineeringRunRow { readonly runId:string; readonly engineVersion:string; readonly createdAtIso:string; readonly inputSnapshotHash:string|null; readonly executionStatus:'EXECUTED'|'BLOCKED'; readonly completeness:'complete'|'incomplete'; readonly inputJson:string; readonly resultJson:string; readonly method:'tolue-engineering-analysis-orchestrator-v6'; }
export interface EngineeringRunHistoryItem { readonly runId:string; readonly engineVersion:string; readonly createdAtIso:string; readonly inputSnapshotHash:string|null; readonly executionStatus:'EXECUTED'|'BLOCKED'; readonly completeness:'complete'|'incomplete'; }
export interface EngineeringRunRowStore { readonly insertEngineeringRun:(row:Readonly<PersistedEngineeringRunRow>)=>void; readonly readEngineeringRun:(runId:string)=>Readonly<PersistedEngineeringRunRow>|null; readonly listEngineeringRuns:()=>readonly Readonly<PersistedEngineeringRunRow>[]; }
export interface PersistedEngineeringRun { readonly input:Readonly<SimulationRunInput>; readonly result:Readonly<EngineeringAnalysisResult>; }

function validatePair(input:Readonly<SimulationRunInput>,result:Readonly<EngineeringAnalysisResult>):void{if(!input.runId.trim()||input.runId!==result.runId)throw new Error('PERSISTENCE-RUN-ID-001');if(!input.engineVersion.trim()||input.engineVersion!==result.engineVersion)throw new Error('PERSISTENCE-ENGINE-VERSION-001');if(!Number.isFinite(Date.parse(input.createdAtIso)))throw new Error('PERSISTENCE-CREATED-AT-001');if(result.executionStatus==='EXECUTED'&&!result.inputSnapshotHash)throw new Error('PERSISTENCE-INPUT-HASH-001');if(result.executionStatus==='BLOCKED'&&result.inputSnapshotHash!==null)throw new Error('PERSISTENCE-BLOCKED-HASH-001');}
function rowFor(input:Readonly<SimulationRunInput>,result:Readonly<EngineeringAnalysisResult>):Readonly<PersistedEngineeringRunRow>{return Object.freeze({runId:result.runId,engineVersion:result.engineVersion,createdAtIso:input.createdAtIso,inputSnapshotHash:result.inputSnapshotHash,executionStatus:result.executionStatus,completeness:result.completeness,inputJson:JSON.stringify(input),resultJson:JSON.stringify(result),method:result.method});}
function sameRow(left:Readonly<PersistedEngineeringRunRow>,right:Readonly<PersistedEngineeringRunRow>):boolean{return left.runId===right.runId&&left.engineVersion===right.engineVersion&&left.createdAtIso===right.createdAtIso&&left.inputSnapshotHash===right.inputSnapshotHash&&left.executionStatus===right.executionStatus&&left.completeness===right.completeness&&left.inputJson===right.inputJson&&left.resultJson===right.resultJson&&left.method===right.method;}
function parseAndValidateRow(row:Readonly<PersistedEngineeringRunRow>):Readonly<PersistedEngineeringRun>{let input:SimulationRunInput;let result:EngineeringAnalysisResult;try{input=JSON.parse(row.inputJson) as SimulationRunInput;result=JSON.parse(row.resultJson) as EngineeringAnalysisResult;}catch{throw new Error('PERSISTENCE-RUN-JSON-INTEGRITY-001');}try{validatePair(input,result);}catch{throw new Error('PERSISTENCE-RUN-ROW-INTEGRITY-001');}if(row.runId!==input.runId||row.runId!==result.runId||row.engineVersion!==input.engineVersion||row.engineVersion!==result.engineVersion||row.createdAtIso!==input.createdAtIso||row.executionStatus!==result.executionStatus||row.completeness!==result.completeness||row.inputSnapshotHash!==result.inputSnapshotHash||row.method!==result.method)throw new Error('PERSISTENCE-RUN-ROW-INTEGRITY-001');return Object.freeze({input:Object.freeze(input),result:Object.freeze(result)});}
function validateHistoryRow(row:Readonly<PersistedEngineeringRunRow>):void{parseAndValidateRow(row);}

export function createEngineeringRunRepository(store:Readonly<EngineeringRunRowStore>){return Object.freeze({
save(input:Readonly<SimulationRunInput>,result:Readonly<EngineeringAnalysisResult>):void{validatePair(input,result);const next=rowFor(input,result);const existing=store.readEngineeringRun(next.runId);if(existing){if(sameRow(existing,next))return;throw new Error('PERSISTENCE-RUN-IMMUTABLE-001');}store.insertEngineeringRun(next);},
findByRunId(runId:string):Readonly<PersistedEngineeringRun>|null{if(!runId.trim())throw new Error('PERSISTENCE-RUN-ID-LOOKUP-001');const row=store.readEngineeringRun(runId);if(!row)return null;return parseAndValidateRow(row);},
listHistory():readonly Readonly<EngineeringRunHistoryItem>[] {return Object.freeze(store.listEngineeringRuns().map(row=>{validateHistoryRow(row);return Object.freeze({runId:row.runId,engineVersion:row.engineVersion,createdAtIso:row.createdAtIso,inputSnapshotHash:row.inputSnapshotHash,executionStatus:row.executionStatus,completeness:row.completeness});}));},
});}
export type EngineeringRunRepository=ReturnType<typeof createEngineeringRunRepository>;
