import { describe, expect, it } from 'vitest';
import type { EngineeringAnalysisResult } from '../../../engineering/core/engineeringAnalysis';
import type { SimulationRunInput } from '../../../engineering/core/simulationRun';
import { createEngineeringRunRepository, type PersistedEngineeringRunRow } from './engineeringRunRepository';
const input={runId:'run-001',engineVersion:'engine-1',createdAtIso:'2026-09-09T00:00:00.000Z'} as unknown as SimulationRunInput;
const blocked={runId:'run-001',engineVersion:'engine-1',readiness:{status:'BLOCKED',canExecute:false,findings:[],method:'tolue-engineering-readiness-gate-v2'},executionStatus:'BLOCKED',inputSnapshotHash:null,simulation:null,resultCenter:null,diagnostics:null,pumpabilityDecision:null,finalOutput:null,reportExport:null,pdfExportRequest:null,visualization3d:null,completeness:'incomplete',method:'tolue-engineering-analysis-orchestrator-v6'} as EngineeringAnalysisResult;
const store=(rows:PersistedEngineeringRunRow[])=>({insertEngineeringRun:(value:Readonly<PersistedEngineeringRunRow>)=>{if(rows.some(row=>row.runId===value.runId))throw new Error('SQLITE-CONSTRAINT-RUN-ID');rows.push(value);},readEngineeringRun:(runId:string)=>rows.find(row=>row.runId===runId)??null,listEngineeringRuns:()=>rows});
describe('engineering run repository',()=>{
it('persists and restores the exact input/result pair',()=>{const rows:PersistedEngineeringRunRow[]=[];const repository=createEngineeringRunRepository(store(rows));repository.save(input,blocked);const persisted=rows.at(0);expect(persisted).toBeDefined();if(!persisted)throw new Error('TEST-PERSISTED-RUN-001');expect(persisted.runId).toBe('run-001');expect(persisted.inputSnapshotHash).toBeNull();const restored=repository.findByRunId('run-001');expect(restored?.input.runId).toBe(input.runId);expect(restored?.result).toEqual(blocked);});
it('round-trips spatial pipeline geometry and connectivity without projection or field loss',()=>{const spatialInput={...input,pipeline:{segments:[{id:'S-001',kind:'straight',lengthM:13,pipeRadiusM:0.05,elevationChangeM:12,spatial:{startPoint:{xM:0,yM:0,zM:0},endPoint:{xM:3,yM:4,zM:12}}},{id:'S-002',kind:'straight',lengthM:5,pipeRadiusM:0.05,elevationChangeM:0,spatial:{startPoint:{xM:3,yM:4,zM:12},endPoint:{xM:6,yM:8,zM:12},connectedFromSegmentId:'S-001'}}]}} as unknown as SimulationRunInput;const rows:PersistedEngineeringRunRow[]=[];const repository=createEngineeringRunRepository(store(rows));repository.save(spatialInput,blocked);const persisted=rows.at(0);expect(persisted).toBeDefined();if(!persisted)throw new Error('TEST-PERSISTED-SPATIAL-001');const raw=JSON.parse(persisted.inputJson) as SimulationRunInput;expect(raw.pipeline.segments[0]?.spatial?.endPoint).toEqual({xM:3,yM:4,zM:12});expect(raw.pipeline.segments[1]?.spatial?.connectedFromSegmentId).toBe('S-001');const restored=repository.findByRunId('run-001');expect(restored?.input.pipeline.segments).toEqual(spatialInput.pipeline.segments);});
it('treats an exact duplicate save as idempotent without rewriting history',()=>{const rows:PersistedEngineeringRunRow[]=[];const repository=createEngineeringRunRepository(store(rows));repository.save(input,blocked);repository.save(input,blocked);expect(rows).toHaveLength(1);});
it('fails closed when an existing runId is reused with different content',()=>{const rows:PersistedEngineeringRunRow[]=[];const repository=createEngineeringRunRepository(store(rows));repository.save(input,blocked);expect(()=>repository.save({...input,createdAtIso:'2026-09-09T00:00:01.000Z'},blocked)).toThrow('PERSISTENCE-RUN-IMMUTABLE-001');expect(rows).toHaveLength(1);expect(rows[0]!.createdAtIso).toBe(input.createdAtIso);});
it('returns detached metadata-only history in store order',()=>{const rows:PersistedEngineeringRunRow[]=[];const repository=createEngineeringRunRepository(store(rows));repository.save(input,blocked);const history=repository.listHistory();expect(history).toEqual([{runId:'run-001',engineVersion:'engine-1',createdAtIso:input.createdAtIso,inputSnapshotHash:null,executionStatus:'BLOCKED',completeness:'incomplete'}]);expect(Object.isFrozen(history)).toBe(true);expect(Object.isFrozen(history[0])).toBe(true);expect(history[0]).not.toHaveProperty('inputJson');expect(history[0]).not.toHaveProperty('resultJson');});
it('rejects run identity mismatch before writing',()=>{const repository=createEngineeringRunRepository(store([]));expect(()=>repository.save(input,{...blocked,runId:'other-run'})).toThrow('PERSISTENCE-RUN-ID-001');});
it('detects persisted row metadata corruption on read and history',()=>{const row:PersistedEngineeringRunRow={runId:'run-001',engineVersion:'engine-corrupt',createdAtIso:input.createdAtIso,inputSnapshotHash:null,executionStatus:'BLOCKED',completeness:'incomplete',inputJson:JSON.stringify(input),resultJson:JSON.stringify(blocked),method:'tolue-engineering-analysis-orchestrator-v6'};const repository=createEngineeringRunRepository(store([row]));expect(()=>repository.findByRunId('run-001')).toThrow('PERSISTENCE-RUN-ROW-INTEGRITY-001');expect(()=>repository.listHistory()).toThrow('PERSISTENCE-RUN-ROW-INTEGRITY-001');});
it('detects created-at and completeness metadata corruption',()=>{for(const patch of [{createdAtIso:'2026-09-10T00:00:00.000Z'},{completeness:'complete' as const}]){const row:PersistedEngineeringRunRow={runId:'run-001',engineVersion:'engine-1',createdAtIso:input.createdAtIso,inputSnapshotHash:null,executionStatus:'BLOCKED',completeness:'incomplete',inputJson:JSON.stringify(input),resultJson:JSON.stringify(blocked),method:'tolue-engineering-analysis-orchestrator-v6',...patch};const repository=createEngineeringRunRepository(store([row]));expect(()=>repository.findByRunId('run-001')).toThrow('PERSISTENCE-RUN-ROW-INTEGRITY-001');}});
it('fails closed on malformed persisted JSON',()=>{const row:PersistedEngineeringRunRow={runId:'run-001',engineVersion:'engine-1',createdAtIso:input.createdAtIso,inputSnapshotHash:null,executionStatus:'BLOCKED',completeness:'incomplete',inputJson:'{broken',resultJson:JSON.stringify(blocked),method:'tolue-engineering-analysis-orchestrator-v6'};const repository=createEngineeringRunRepository(store([row]));expect(()=>repository.findByRunId('run-001')).toThrow('PERSISTENCE-RUN-JSON-INTEGRITY-001');expect(()=>repository.listHistory()).toThrow('PERSISTENCE-RUN-JSON-INTEGRITY-001');});
});
